export type VideoItem = {
  id: string;
  title: string;
  youtubeId?: string;
  fileUrl?: string; // optional direct URL (mp4, webm) for native playback
  topic: string;
  description?: string;
};

export const videoLibrary: VideoItem[] = [
  // Linked Lists
  {
    id: 'll-1',
    topic: 'Linked Lists',
    title: 'Linked List Data Structure - Explained',
    youtubeId: 'njTh_OwMljA',
  },
  {
    id: 'll-2',
    topic: 'Linked Lists',
    title: 'Linked List problems & interview patterns',
    youtubeId: 'UaQxnl2jVnI',
  },

  // Stacks & Queues
  {
    id: 'st-1',
    topic: 'Stacks & Queues',
    title: 'Stacks and Queues - Implementation & Problems',
    youtubeId: 'wjI1WNcIntg',
  },

  // Trees
  {
    id: 'tree-1',
    topic: 'Trees',
    title: 'Binary Trees & Traversals',
    youtubeId: 'vRbi1Y3h1X0',
  },

  // Graphs
  {
    id: 'graph-1',
    topic: 'Graphs',
    title: 'Graph algorithms - BFS & DFS',
    youtubeId: 'pcKY4hjDrxk',
  },

  // DP
  {
    id: 'dp-1',
    topic: 'Dynamic Programming',
    title: 'Dynamic Programming - Beginner to Advanced',
    youtubeId: 'OQ5jsbhAv_M',
  },

  // Marker for automated playlist imports. Tools/scripts can insert generated items
  // between IMPORTED_VIDEOS_START and IMPORTED_VIDEOS_END. Do not remove these markers.
  // IMPORTED_VIDEOS_START

  {
    id: "yt-3_x_Fb31NLE",
    topic: "Arrays",
    title: "WHAT IS ARRAY? | Array Data Structures | DSA Course | GeeksforGeeks",
    youtubeId: "3_x_Fb31NLE",
    description: "GeeksforGeeks brings you a deep dive into the world of ARRAYS in our latest DSA course video!\n\n✨ As one of the most important data structures in DSA, ARRAYS play a fundamental role in organizing and manipulating data. Gain a profound understanding of arrays, delving into the intricacies of contiguous memory allocation and the difference between static and dynamic arrays. Unravel the mystery of array declaration and join us for a detailed exploration of basic operations like insertion and accessing an element (highlighting its efficient O(1) time complexity). \n \n🚀 This comprehensive array tutorial is tailored for coding interviews and competitive programming, with real-world examples and hands-on insights to fortify your skill set.\n\n\n💻 Practice Array Problems: https://practice.geeksforgeeks.org/explore?page=1&category=Arrays&sortBy=submissions&utm_source=youtube&utm_medium=main_channel&utm_campaign=dsa_new\n\n📚 Read More about Arrays: https://www.geeksforgeeks.org/array-data-structure/\n\nhttps://www.geeksforgeeks.org/array-data-structure-guide/\n-------------------------------------------------------------------------\n\n⏰ Time Stamps:\n0:00 - Introduction to Arrays\n1:50 - Contiguous Memory Allocation of Arrays\n3:30 - Difference Between Static & Dynamic arrays \n4:40 - Declaring an Array - Array Declaration\n6:05 - Inserting an Element in an Array\n7:20 - Array Bonus Fact - Accessing Element in an Array in O(1)\n\n-------------------------------------------------------------------------\n\n🔴 Check out the next video on Solving Array Practice Problems: https://youtu.be/J7EhXvnixRM?si=Swnh_wOAgvdRVXmX\n\n🔴 Check out the Full DSA Course Playlist: https://youtube.com/playlist?list=PLqM7alHXFySHWUSBXUW9eq-ajb2JLoFNS&si=m_4B8bdS8dSJ9W6m\n\n-------------------------------------------------------------------------\n\n📖 Want to Learn more about Data Structures and Algorithms? \nCheck out our Data Structures and Algorithms - Self Paced Course Now!: https://www.geeksforgeeks.org/courses/dsa-self-paced?utm_source=youtube&utm_medium=main_channel&utm_campaign=dsa_new\n\n📚 Explore Our Courses: https://practice.geeksforgeeks.org/courses?utm_source=youtube&utm_medium=main_channel&utm_campaign=dsa_new\n\n-------------------------------------------------------------------------\n\nFollow us for more fun, knowledge, and resources:\n\n💬 Twitter- https://twitter.com/geeksforgeeks \n🧑‍💼 LinkedIn- https://www.linkedin.com/company/geeksforgeeks\n📷 Instagram- https://www.instagram.com/geeks_for_geeks/?hl=en \n💌 Telegram- https://t.me/s/geeksforgeeks_official \n\n📱 Download GeeksforGeeks' Official App: https://geeksforgeeksapp.page.link/gfg-app\n\n\nRelated Queries:\nDSA course\nArray in data structures \narrays in dsa\nDSA free course\nintroduction to arrays\narray implementation \narray data structure interview question\narray practice problems\narray interview questions\narray in c language\narray in java\narray in python\nfundamentals of array\ngeeksforgeeks DSA\narray data structure GFG\n\n\n#dsa #datastructures #arrays #arrayoperations #GeeksforGeeks #GfG #datastructuresandalgorithms #insertioninarray #staticarray #dynamicarray #arrayturorials",
  },
  {
    id: "yt-J7EhXvnixRM",
    topic: "Arrays",
    title: "ARRAY PRACTICE PROBLEMS | Must do Array Questions | DSA Problems | GeeksforGeeks",
    youtubeId: "J7EhXvnixRM",
    description: "🚀 Join GeeksforGeeks in our next DSA Course video as we delve into the fascinating world of ARRAY PRACTICE PROBLEMS!\n\nUncover the secrets of solving well-known array problems that are frequently asked in interviews. We'll not only walk you through the problems but also provide strategic insights on how to approach and master them. \n\n🕵️‍♂️ Elevate your problem-solving skills and gain a deeper understanding of Arrays and Array Manipulation. \nPrepare to conquer your next interview with confidence and finesse by practicing our DSA Problems.\n\nRead More: https://www.geeksforgeeks.org/top-50-array-coding-problems-for-interviews/\n\n\n💻 Following are the Practice Problems we have discussed in the video (suggest you to try it yourself):\n00:00 - Introduction\n\n00:30 - Leaders in an array: https://practice.geeksforgeeks.org/problems/leaders-in-an-array-1587115620/1?utm_source=youtube&utm_medium=main_channel&utm_campaign=dsa_new\n\n02:40 - Sort an array 0s, 1s, and 2s : https://practice.geeksforgeeks.org/problems/sort-an-array-of-0s-1s-and-2s4231/1?utm_source=youtube&utm_medium=main_channel&utm_campaign=dsa_new\n\n04:23 - Count More than n/k Occurences: https://practice.geeksforgeeks.org/problems/count-element-occurences/1?utm_source=youtube&utm_medium=main_channel&utm_campaign=dsa_new\n\n06:25 - Kadane's Algorithm: https://practice.geeksforgeeks.org/problems/kadanes-algorithm-1587115620/1?utm_source=youtube&utm_medium=main_channel&utm_campaign=dsa_new\n\n08:14 - Smallest Positive missing number: https://practice.geeksforgeeks.org/problems/smallest-positive-missing-number-1587115621/1?utm_source=youtube&utm_medium=main_channel&utm_campaign=dsa_new\n\n-------------------------------------------------------------------------\n\n🔴 What is Queue? Watch Now!: https://youtu.be/J7EhXvnixRM?si=Swnh_wOAgvdRVXmX\n\n🔴 Check out the Full DSA Course Playlist: https://youtube.com/playlist?list=PLqM7alHXFySHWUSBXUW9eq-ajb2JLoFNS&si=m_4B8bdS8dSJ9W6m\n\n-------------------------------------------------------------------------\n\n📖 Want to Learn more about Data Structures and Algorithms? \nCheck out our Data Structures and Algorithms - Self Paced Course Now!: https://www.geeksforgeeks.org/courses/dsa-self-paced?utm_source=youtube&utm_medium=main_channel&utm_campaign=dsa_new\n\n📚 Explore Our Courses: https://practice.geeksforgeeks.org/courses?utm_source=youtube&utm_medium=main_channel&utm_campaign=dsa_new\n\n-------------------------------------------------------------------------\n\nFollow us for more fun, knowledge, and resources:\n\n💬 Twitter- https://twitter.com/geeksforgeeks \n🧑‍💼 LinkedIn- https://www.linkedin.com/company/geeksforgeeks\n📷 Instagram- https://www.instagram.com/geeks_for_geeks/?hl=en \n💌 Telegram- https://t.me/s/geeksforgeeks_official \n\n📱 Download GeeksforGeeks' Official App: https://geeksforgeeksapp.page.link/gfg-app\n\n\n#GeeksforGeeks #GfG #datastructures #arrays #arraypracticeproblems #arrayturorials #practiceproblems #arraymanipulation #arrayquestions #arrayinterviewproblems #datastructuresandalgorithms #dsa",
  },
  {
    id: "yt-xtfj4-r_Ahs",
    topic: "Arrays",
    title: "Longest Span with same Sum in two Binary arrays | GeeksforGeeks",
    youtubeId: "xtfj4-r_Ahs",
    description: "Here's you next clue  - Our comprehensive guide to acing placements in your dream company.\n\nRead More: https://www.geeksforgeeks.org/longest-span-sum-two-binary-arrays/\n\nExplanation for the Article http://www.geeksforgeeks.org/longest-span-sum-two-binary-arrays/\n\nThis video is contributed by Sephiri.",
  },
  {
    id: "yt-EQQp4B_CU5Q",
    topic: "Arrays",
    title: "Union and Intersection of two sorted arrays | GeeksforGeeks",
    youtubeId: "EQQp4B_CU5Q",
    description: "Explanation for the article: http://www.geeksforgeeks.org/union-and-intersection-of-two-sorted-arrays-2/\n\nRead More: https://www.geeksforgeeks.org/union-and-intersection-of-two-sorted-arrays-2/\n\nThis video is contributed by Harshit Jain.",
  },
  {
    id: "yt-hoceGcqQczM",
    topic: "Arrays",
    title: "Find the minimum distance between two numbers | GeeksforGeeks",
    youtubeId: "hoceGcqQczM",
    description: "Explanation for the article: http://www.geeksforgeeks.org/find-the-minimum-distance-between-two-numbers/\n\nPractice Problem Online Judge: http://practice.geeksforgeeks.org/problems/minimum-distance-between-two-numbers/1\n\nThis video is contributed by Harshit Jain.",
  },
  {
    id: "yt-NyRZm1pzNmQ",
    topic: "Arrays",
    title: "Leaders in an array | GeeksforGeeks",
    youtubeId: "NyRZm1pzNmQ",
    description: "Explanation for the article: http://www.geeksforgeeks.org/leaders-in-an-array/\n\nRead More: https://www.geeksforgeeks.org/leaders-in-an-array/\n\nThis video is contributed by Harshit Jain.\n#geeksforgeeks",
  },
  {
    id: "yt-uwogtyFiDLg",
    topic: "Arrays",
    title: "Majority Element | GeeksforGeeks",
    youtubeId: "uwogtyFiDLg",
    description: "Explanation for the article: http://www.geeksforgeeks.org/majority-element/\n\nThis video is contributed by Harshit Jain.",
  },
  {
    id: "yt-hySR1exD5PE",
    topic: "Arrays",
    title: "Find the Number Occurring Odd Number of Times | GeeksforGeeks",
    youtubeId: "hySR1exD5PE",
    description: "Explanation for the article: http://www.geeksforgeeks.org/find-the-number-occurring-odd-number-of-times/\n\nRead More: https://www.geeksforgeeks.org/find-the-number-occurring-odd-number-of-times/\n\nThis video is contributed by Harshit Jain.",
  },
  {
    id: "yt-bLb8e83OK7o",
    topic: "Arrays",
    title: "Replace every element with the greatest element on right side | GeeksforGeeks",
    youtubeId: "bLb8e83OK7o",
    description: "Explanation for the article: http://www.geeksforgeeks.org/replace-every-element-with-the-greatest-on-right-side/\n\nThis video is contributed by Harshit Jain.",
  },
  {
    id: "yt-hASRzBXY5kY",
    topic: "Arrays",
    title: "Find a Fixed Point in a given array | GeeksforGeeks",
    youtubeId: "hASRzBXY5kY",
    description: "Explanation for the article: http://www.geeksforgeeks.org/find-a-fixed-point-in-a-given-array/\n\nThis video is contributed by Harshit Jain.",
  },
  {
    id: "yt-NFvAD5na5oU",
    topic: "Arrays",
    title: "Find a Peak Element | GeeksforGeeks",
    youtubeId: "NFvAD5na5oU",
    description: "Explanation for the article: http://www.geeksforgeeks.org/find-a-peak-in-a-given-array/\n\nThis video is contributed by Harshit Jain.",
  },
  {
    id: "yt-eMuC2LCoMvU",
    topic: "Arrays",
    title: "Count Strictly Increasing Subarrays | GeeksforGeeks",
    youtubeId: "eMuC2LCoMvU",
    description: "Explanation for the article: http://www.geeksforgeeks.org/count-strictly-increasing-subarrays/\n\nKnow More: https://www.geeksforgeeks.org/count-strictly-increasing-subarrays/\n\nThis video is contributed by Harshit Jain.",
  },
  {
    id: "yt-6sz42JCApIw",
    topic: "Arrays",
    title: "Private video",
    youtubeId: "6sz42JCApIw",
    description: "This video is private.",
  },
  {
    id: "yt-oNtexwxSZ3s",
    topic: "Arrays",
    title: "Pythagorean Triplet in an array | GeeksforGeeks",
    youtubeId: "oNtexwxSZ3s",
    description: "Explanation for the article: http://www.geeksforgeeks.org/find-pythagorean-triplet-in-an-unsorted-array/\n\nRead More: https://www.geeksforgeeks.org/find-pythagorean-triplet-in-an-unsorted-array/\n\nPractice Problem Online Judge: http://practice.geeksforgeeks.org/problems/pythagorean-triplet/0\n\nThis video is contributed by Harshit Jain.",
  },
  {
    id: "yt-DR7NgPnErxI",
    topic: "Arrays",
    title: "Segregate 0s and 1s in an array | GeeksforGeeks",
    youtubeId: "DR7NgPnErxI",
    description: "Explanation for the article: http://www.geeksforgeeks.org/segregate-0s-and-1s-in-an-array-by-traversing-array-once/\n\nRead more: https://www.geeksforgeeks.org/segregate-0s-and-1s-in-an-array-by-traversing-array-once/\n\nThis video is contributed by Harshit Jain.",
  },
  {
    id: "yt-I7Nz1XzzPYc",
    topic: "Arrays",
    title: "Given an array A[] and a number x, check for pair in A[] with sum as x | GeeksforGeeks",
    youtubeId: "I7Nz1XzzPYc",
    description: "Explanation for the article: http://www.geeksforgeeks.org/write-a-c-program-that-given-a-set-a-of-n-numbers-and-another-number-x-determines-whether-or-not-there-exist-two-elements-in-s-whose-sum-is-exactly-x/\n\nThis video is contributed by Harshit Jain.",
  },
  {
    id: "yt-qjNVJTUge7s",
    topic: "Arrays",
    title: "Print missing elements that lie in range 0 – 99 | GeeksforGeeks",
    youtubeId: "qjNVJTUge7s",
    description: "Explanation for the article: http://www.geeksforgeeks.org/print-missing-elements-that-lie-in-range-0-99/\n\nThis video is contributed by Harshit Jain.",
  },
  {
    id: "yt-Nzm9emAkSCM",
    topic: "Arrays",
    title: "Floor and Ceiling in a sorted array | GeeksforGeeks",
    youtubeId: "Nzm9emAkSCM",
    description: "Explanation for the article: http://www.geeksforgeeks.org/search-floor-and-ceil-in-a-sorted-array/\n\nThis video is contributed by Harshit Jain.\n\nRead More: https://www.geeksforgeeks.org/ceiling-in-a-sorted-array/",
  },
  {
    id: "yt-BjODIZvW4no",
    topic: "Arrays",
    title: "Implement two stacks in an array | GeeksforGeeks",
    youtubeId: "BjODIZvW4no",
    description: "Explanation for the article: http://www.geeksforgeeks.org/implement-two-stacks-in-an-array/\n\nRead More: https://www.geeksforgeeks.org/implement-two-stacks-in-an-array/\n\nThis video is contributed by Harshit Jain.",
  },
  {
    id: "yt-Cr20pvlhqBU",
    topic: "Arrays",
    title: "Find minimum difference between any two elements | GeeksforGeeks",
    youtubeId: "Cr20pvlhqBU",
    description: "Explanation for the article: http://www.geeksforgeeks.org/find-minimum-difference-pair/\n\nThis video is contributed by Harshit Jain.\n\nRead More: https://www.geeksforgeeks.org/find-minimum-difference-pair/",
  },
  {
    id: "yt-HuZJqRDOPo0",
    topic: "Arrays",
    title: "Find duplicates in O(n) time and O(1) extra space | GeeksforGeeks",
    youtubeId: "HuZJqRDOPo0",
    description: "Explanation for the article: http://www.geeksforgeeks.org/find-duplicates-in-on-time-and-constant-extra-space/\n\nThis video is contributed by Harshit Jain.\n\nRead More: https://www.geeksforgeeks.org/find-duplicates-in-on-time-and-constant-extra-space/",
  },
  {
    id: "yt-dx8twFuPgvg",
    topic: "Arrays",
    title: "Find lost element from a duplicated array | GeeksforGeeks",
    youtubeId: "dx8twFuPgvg",
    description: "Explanation for the article: http://www.geeksforgeeks.org/find-lost-element-from-a-duplicated-array/\n\nThis video is contributed by Harshit Jain.\n\nRead More: https://www.geeksforgeeks.org/find-lost-element-from-a-duplicated-array/",
  },
  {
    id: "yt-HUwYrtrOcd0",
    topic: "Arrays",
    title: "Two elements whose sum is closest to zero | GeeksforGeeks",
    youtubeId: "HUwYrtrOcd0",
    description: "Explanation for the article: http://www.geeksforgeeks.org/two-elements-whose-sum-is-closest-to-zero/\n\nThis video is contributed by Harshit Jain.",
  },
  {
    id: "yt-k4vMVTp6AuI",
    topic: "Arrays",
    title: "Maximum Length Bitonic Subarray | GeeksforGeeks",
    youtubeId: "k4vMVTp6AuI",
    description: "Explanation for the article: http://www.geeksforgeeks.org/maximum-length-bitonic-subarray/\n\nThis video is contributed by Harshit Jain.",
  },
  {
    id: "yt-AXlPTwCzpAo",
    topic: "Arrays",
    title: "Count minimum steps to get the given desired array | GeeksforGeeks",
    youtubeId: "AXlPTwCzpAo",
    description: "Explanation for the article: http://www.geeksforgeeks.org/count-minimum-steps-get-given-desired-array/\n\nThis video is contributed by Harshit Jain.",
  },
  {
    id: "yt-wBGxPHXAPM4",
    topic: "Arrays",
    title: "Find minimum number of merge operations to make an array palindrome | GeeksforGeeks",
    youtubeId: "wBGxPHXAPM4",
    description: "Explanation for the article: http://www.geeksforgeeks.org/find-minimum-number-of-merge-operations-to-make-an-array-palindrome/\n\nThis video is contributed by Harshit Jain.",
  },
  {
    id: "yt-0jXTju134Hw",
    topic: "Arrays",
    title: "Move all zeroes to end of array | GeeksforGeeks",
    youtubeId: "0jXTju134Hw",
    description: "Explanation for the article: http://www.geeksforgeeks.org/move-zeroes-end-array/\n\nThis video is contributed by Harshit Jain.\n\nRead More: https://www.geeksforgeeks.org/move-zeroes-end-array/",
  },
  {
    id: "yt-SO0bwMziLlU",
    topic: "Arrays",
    title: "Maximum difference between two elements (larger element appears after smaller) | GeeksforGeeks",
    youtubeId: "SO0bwMziLlU",
    description: "Explanation for the article: http://www.geeksforgeeks.org/maximum-difference-between-two-elements/\n\nThis video is contributed by Harshit Jain.",
  },
  {
    id: "yt-KBqbhoIn8Og",
    topic: "Arrays",
    title: "Write a program to reverse an array or string | GeeksforGeeks",
    youtubeId: "KBqbhoIn8Og",
    description: "Explanation for the article: http://www.geeksforgeeks.org/write-a-program-to-reverse-an-array-or-string/\n\nThis video is contributed by Arjun Tyagi.\nRead More: https://www.geeksforgeeks.org/program-to-reverse-an-array/\n\nBackground Music: https://www.youtube.com/channel/UCmqmVRMWMj8pIW9K5bfuBjw\n\n#geeksforgeeks",
  },
  {
    id: "yt-WdgAKCnWnwA",
    topic: "Arrays",
    title: "Merge Overlapping Intervals | GeeksforGeeks",
    youtubeId: "WdgAKCnWnwA",
    description: "Explanation for the article: http://www.geeksforgeeks.org/merging-intervals/\n\nThis video is contributed by Harshit Jain.\n\nRead More: https://www.geeksforgeeks.org/merging-intervals/",
  },
  {
    id: "yt-uN5QUBHUQaM",
    topic: "Arrays",
    title: "Search an element in a sorted and rotated array | D E Shaw Interview Questions | GeeksforGeeks",
    youtubeId: "uN5QUBHUQaM",
    description: "Explanation for the article: http://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/\n\nThis video is contributed by Harshit Jain.\n\nRead More: https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/",
  },
  {
    id: "yt-fYR0X_MP4Ks",
    topic: "Arrays",
    title: "Convert array into Zig-Zag fashion | GeeksforGeeks",
    youtubeId: "fYR0X_MP4Ks",
    description: "Explanation for the article: http://www.geeksforgeeks.org/convert-array-into-zig-zag-fashion/\n\nThis video is contributed by Harshit Jain.",
  },
  {
    id: "yt-5AoM96b9BZg",
    topic: "Arrays",
    title: "Reverse an array without affecting special characters | GeeksforGeeks",
    youtubeId: "5AoM96b9BZg",
    description: "Explanation for the article: http://www.geeksforgeeks.org/reverse-an-array-without-affecting-special-characters/\n\nThis video is contributed by Harshit Jain.",
  },
  {
    id: "yt-7nso5Dgc6CI",
    topic: "Arrays",
    title: "Count triplets with sum smaller than a given value | GeeksforGeeks",
    youtubeId: "7nso5Dgc6CI",
    description: "Explanation for the article: http://www.geeksforgeeks.org/count-triplets-with-sum-smaller-that-a-given-value/\n\nThis video is contributed by Harshit Jain.",
  },
  {
    id: "yt-O7gf0a4c_5c",
    topic: "Arrays",
    title: "Length of the largest subarray with contiguous elements | Set 1 | GeeksforGeeks",
    youtubeId: "O7gf0a4c_5c",
    description: "Explanation for the article: http://www.geeksforgeeks.org/length-largest-subarray-contiguous-elements-set-1/\n\nThis video is contributed by Harshit Jain.",
  },
  {
    id: "yt-JaosdXkUWTs",
    topic: "Arrays",
    title: "Stock Buy Sell to Maximize Profit | GeeksforGeeks",
    youtubeId: "JaosdXkUWTs",
    description: "Explanation for the article: http://www.geeksforgeeks.org/stock-buy-sell/\n\nThis video is contributed by Harshit Jain.\n\nRead More: https://www.geeksforgeeks.org/stock-buy-sell/",
  },
  {
    id: "yt-ilKK8bimP24",
    topic: "Arrays",
    title: "Find common elements in three sorted arrays | GeeksforGeeks",
    youtubeId: "ilKK8bimP24",
    description: "GeeksforGeeks Article: http://www.geeksforgeeks.org/find-common-elements-three-sorted-arrays/\n\nPractice Problem: http://practice.geeksforgeeks.org/problems/common-elements-in-three-arrays/0\n\nThis video is contributed by Aditi Bainss\n\nPlease Like, Comment, Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-6w60Zi1NtL8",
    topic: "Arrays",
    title: "Maximum sum such that no two elements are adjacent | GeeksforGeeks",
    youtubeId: "6w60Zi1NtL8",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/maximum-sum-such-that-no-two-elements-are-adjacent/\n\nPractice Problem Online Judge: http://practice.geeksforgeeks.org/problems/max-sum-without-adjacents/0\n\nThis video is contributed by Shubham Kumar\n\nRead More: https://www.geeksforgeeks.org/maximum-sum-such-that-no-two-elements-are-adjacent/\n\nPlease Like, Comment and Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-vSOkxXxIXZE",
    topic: "Arrays",
    title: "Search, insert and delete in an unsorted array | GeeksforGeeks",
    youtubeId: "vSOkxXxIXZE",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/search-insert-and-delete-in-an-unsorted-array/\n\nPractice Problem Online Judge: http://practice.geeksforgeeks.org/problems/operating-an-array/1\n\nThis video is contributed by Shubham Kumar\n\nRead More: https://www.geeksforgeeks.org/search-insert-and-delete-in-an-unsorted-array/\n\nPlease Like, Comment and Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)\n#geeksforgeeks",
  },
  {
    id: "yt-PrJdyDMP8VU",
    topic: "Arrays",
    title: "Find a pair with maximum product in array of Integers | GeeksforGeeks",
    youtubeId: "PrJdyDMP8VU",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/return-a-pair-with-maximum-product-in-array-of-integers/\n\nPractice Problem Online Judge: http://practice.geeksforgeeks.org/problems/maximum-product-of-two-numbers/0\n\nThis video is contributed by Parikshit Kumar Pruthi\n\nPlease Like, Comment and Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-qODOVGzk6Zc",
    topic: "Arrays",
    title: "Find a pair with the given difference | GeeksforGeeks",
    youtubeId: "qODOVGzk6Zc",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/find-a-pair-with-the-given-difference/\n\nThis video is contributed by Parikshit Kumar Pruthi\n\nPlease Like, Comment and Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-97mCko_YOE0",
    topic: "Arrays",
    title: "Find the largest pair sum in an unsorted array | GeeksforGeeks",
    youtubeId: "97mCko_YOE0",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/find-the-largest-pair-sum-in-an-unsorted-array/\n\nThis video is contributed by Parikshit Kumar Pruthi\n\nPlease Like, Comment and Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-NBXf9vCksuM",
    topic: "Arrays",
    title: "Sort elements by frequency | Set 1 | GeeksforGeeks",
    youtubeId: "NBXf9vCksuM",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/sort-elements-by-frequency/\n\nPractice Problem Online Judge: http://practice.geeksforgeeks.org/problems/sorting-elements-of-an-array-by-frequency/0\n\nThis video is contributed by Parikshit Kumar Pruthi\n\nPlease Like, Comment and Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-YxIiJTnmHJU",
    topic: "Arrays",
    title: "Find the odd appearing element in O(Log n) time | GeeksforGeeks",
    youtubeId: "YxIiJTnmHJU",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/find-the-element-that-odd-number-of-times-in-olog-n-time/\n\nThis video is contributed by Parikshit Kumar Pruthi\n\nPlease Like, Comment and Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-G2qGmOyDzCY",
    topic: "Arrays",
    title: "Count number of occurrences (or frequency) in a sorted array | GeeksforGeeks",
    youtubeId: "G2qGmOyDzCY",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/count-number-of-occurrences-or-frequency-in-a-sorted-array/\n\nPractice Problem Online Judge: http://practice.geeksforgeeks.org/problems/number-of-occurrence/0\n\nRead More: https://www.geeksforgeeks.org/count-number-of-occurrences-or-frequency-in-a-sorted-array/\n\nhttps://www.geeksforgeeks.org/sort-elements-by-frequency/\n\nThis video is contributed by Parikshit Kumar Pruthi\n\nPlease Like, Comment and Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-chYKJGPNEvg",
    topic: "Arrays",
    title: "Number of pairs (x, y) in an array where x^y is greater than y^x | GeeksforGeeks",
    youtubeId: "chYKJGPNEvg",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/find-number-pairs-xy-yx/\n\nPractice Problem Online Judge: http://practice.geeksforgeeks.org/problems/number-of-pairs/0\n\nThis video is contributed by Parikshit Kumar Pruthi\n\nPlease Like, Comment and Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-SX1rtrsJ4R4",
    topic: "Arrays",
    title: "Search, insert and delete in a sorted array | GeeksforGeeks",
    youtubeId: "SX1rtrsJ4R4",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/search-insert-and-delete-in-a-sorted-array/\n\nPractice Problem Online Judge: http://practice.geeksforgeeks.org/problems/operating-a-sorted-array/1\n\nThis video is contributed by Parikshit Kumar Pruthi\n\nPlease Like, Comment and Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-kUJvbYsYwQk",
    topic: "Arrays",
    title: "Find all triplets with zero sum | GeeksforGeeks",
    youtubeId: "kUJvbYsYwQk",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/find-triplets-array-whose-sum-equal-zero/\n\nPractice Problem Online Judge: http://practice.geeksforgeeks.org/problems/find-triplets-with-zero-sum/1\n\nThis video is contributed by Parikshit Kumar Pruthi\n\nPlease Like, Comment and Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-X5UhF3xS5Dk",
    topic: "Arrays",
    title: "Find a triplet that sum to a given value | GeeksforGeeks",
    youtubeId: "X5UhF3xS5Dk",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/find-a-triplet-that-sum-to-a-given-value/\n\nPractice Problem Online Judge: http://practice.geeksforgeeks.org/problems/triplet-sum-in-array/0\n\nThis video is contributed by Shubham Kumar\n\nPlease Like, Comment and Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-p7rnuGsau6g",
    topic: "Arrays",
    title: "Minimum length Unsorted Subarray, sorting which makes the array sorted | GeeksforGeeks",
    youtubeId: "p7rnuGsau6g",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/minimum-length-unsorted-subarray-sorting-which-makes-the-complete-array-sorted/\n\nPractice Problem Online Judge: http://practice.geeksforgeeks.org/problems/length-unsorted-subarray/0\n\nThis video is contributed by Shubham Kumar\n\nPlease Like, Comment and Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-8pTzWRg_evk",
    topic: "Arrays",
    title: "Third largest element in an array of distinct elements | GeeksforGeeks",
    youtubeId: "8pTzWRg_evk",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/third-largest-element-array-distinct-elements/\n\nPractice Problem Online Judge: http://practice.geeksforgeeks.org/problems/third-largest-element/1\n\nThis video is contributed by Parikshit Kumar Pruthi\n\nPlease Like, Comment and Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-QMWBRnolFCU",
    topic: "Arrays",
    title: "Find the pair in array whose sum is closest to x | GeeksforGeeks",
    youtubeId: "QMWBRnolFCU",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/given-sorted-array-number-x-find-pair-array-whose-sum-closest-x/\n\nSimilar Video: https://www.youtube.com/watch?v=I7Nz1XzzPYc\n\nThis video is contributed by Parikshit Kumar Pruthi\n\nPlease Like, Comment and Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-rHwWSYdvAhg",
    topic: "Arrays",
    title: "Queries for greater than and not less than | GeeksforGeeks",
    youtubeId: "rHwWSYdvAhg",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/queries-greater-not-less/\n\nThis video is contributed by Parikshit Kumar Pruthi\n\nPlease Like, Comment and Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-W-t1rjLxvQw",
    topic: "Arrays",
    title: "Equilibrium index of an array | GeeksforGeeks",
    youtubeId: "W-t1rjLxvQw",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/equilibrium-index-of-an-array/\n\nThis video is contributed by Harshit Verma\n\nPlease Like, Comment and Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-8oR5OBW5buk",
    topic: "Arrays",
    title: "Sort an array in wave form | GeeksforGeeks",
    youtubeId: "8oR5OBW5buk",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/sort-array-wave-form-2/\n\nRead More: https://www.geeksforgeeks.org/sort-array-wave-form-2/\n\nPractice Problem Online Judge: http://practice.geeksforgeeks.org/problems/wave-array/0\n\nThis video is contributed by Harshit Verma\n\nRead More: https://www.geeksforgeeks.org/sort-array-wave-form-2/\n\nPlease Like, Comment and Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-xWOoBJUqlbI",
    topic: "Arrays",
    title: "Search in an almost sorted array | GeeksforGeeks",
    youtubeId: "xWOoBJUqlbI",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/search-almost-sorted-array/\n\nRead More: https://www.geeksforgeeks.org/search-almost-sorted-array/\n\nThis video is contributed by Harshit Verma\n\nPlease Like, Comment and Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-090fGlXqKzw",
    topic: "Arrays",
    title: "Find the closest pair from two sorted arrays | GeeksforGeeks",
    youtubeId: "090fGlXqKzw",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/given-two-sorted-arrays-number-x-find-pair-whose-sum-closest-x/\n\nThis video is contributed by Harshit Verma\n\nPlease Like, Comment and Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-OEgfEDR7BNk",
    topic: "Arrays",
    title: "Find the smallest and second smallest elements in an array | GeeksforGeeks",
    youtubeId: "OEgfEDR7BNk",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/to-find-smallest-and-second-smallest-element-in-an-array/\n\nPractice Problem Online Judge: http://practice.geeksforgeeks.org/problems/find-the-smallest-and-second-smallest-element-in-an-array/0\n\nThis video is contributed by Harshit Verma\n\nRead More: https://www.geeksforgeeks.org/to-find-smallest-and-second-smallest-element-in-an-array/\n\nPlease Like, Comment and Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-sKHKHrEfHbI",
    topic: "Arrays",
    title: "Find sum of elements in a given array | GeeksforGeeks",
    youtubeId: "sKHKHrEfHbI",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/program-find-sum-elements-given-array/\n\nPractice Problem Online Judge: http://practice.geeksforgeeks.org/problems/missing-number/0\n\nThis video is contributed by Harshit Verma\n\nPlease Like, Comment and Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-En68ipRaFOU",
    topic: "Arrays",
    title: "Find largest element in an array | GeeksforGeeks",
    youtubeId: "En68ipRaFOU",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/c-program-find-largest-element-array/\n\nPractice Problem Online Judge: http://practice.geeksforgeeks.org/problems/help-a-thief/0\n\nThis video is contributed by Harshit Verma\n\nPlease Like, Comment and Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt--tqsxDpp6NI",
    topic: "Arrays",
    title: "Sum of array elements using recursion | GeeksforGeeks",
    youtubeId: "-tqsxDpp6NI",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/sum-array-elements-using-recursion/\n\nThis video is contributed by Harshit Verma\n\nPlease Like, Comment and Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-LP7YQdT5eps",
    topic: "Arrays",
    title: "Shuffle a given array | GeeksforGeeks",
    youtubeId: "LP7YQdT5eps",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/shuffle-a-given-array/\n\nThis video is contributed by Aditi Bainss\n\nPlease Like, Comment and Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-bvKMZXc0jQU",
    topic: "Arrays",
    title: "Count pairs with given sum | GeeksforGeeks",
    youtubeId: "bvKMZXc0jQU",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/count-pairs-with-given-sum/\n\nPractice Problem Online Judge: http://practice.geeksforgeeks.org/problems/count-pairs-with-given-sum/0\n\nThis video is contributed by Aditi Bainss\n\nPlease Like, Comment and Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-ZNqWgwwpgLU",
    topic: "Arrays",
    title: "Program to cyclically rotate an array by one | GeeksforGeeks",
    youtubeId: "ZNqWgwwpgLU",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/c-program-cyclically-rotate-array-one/\n\nPractice Problem Online Judge: http://practice.geeksforgeeks.org/problems/cyclically-rotate-an-array-by-one/0\n\nThis video is contributed by Aditi Bainss\n\nPlease Like, Comment and Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-QOpU9-l5T7Y",
    topic: "Arrays",
    title: "Reversal algorithm for array rotation | GeeksforGeeks",
    youtubeId: "QOpU9-l5T7Y",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/program-for-array-rotation-continued-reversal-algorithm/\n\nPractice Problem Online Judge: http://practice.geeksforgeeks.org/problems/reversal-algorithm/0\n\nThis video is contributed by Aditi Bainss\n\nRead More: https://www.geeksforgeeks.org/program-for-array-rotation-continued-reversal-algorithm/\n\nPlease Like, Comment and Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-anyBv3m2emQ",
    topic: "Arrays",
    title: "Print Sum Triangle for a given array | GeeksforGeeks",
    youtubeId: "anyBv3m2emQ",
    description: "Sum triangle: A triangle where last row contains elements of given array, every element of second last row contains sum of below two elements and so on.\n\nFind Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/program-to-print-sum-triangle-for-a-given-array/\n\nPractice Problem Online Judge: http://practice.geeksforgeeks.org/problems/sum-triangle-for-given-array/0\n\nThis video is contributed by Sagar Khurana\n\nPlease Like, Comment and Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-8KuFojXysg0",
    topic: "Arrays",
    title: "Find if there is a pair with a given sum in a sorted and rotated array | GeeksforGeeks",
    youtubeId: "8KuFojXysg0",
    description: "Similar Video: https://www.youtube.com/watch?v=I7Nz1XzzPYc\n\nFind Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/given-a-sorted-and-rotated-array-find-if-there-is-a-pair-with-a-given-sum/\n\nThis video is contributed by Aditi Bainss\n\nPlease Like, Comment and Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-Jxq_ejg3Snw",
    topic: "Arrays",
    title: "Convert an array to reduced form | Set 1 (Simple and Hashing) | GeeksforGeeks",
    youtubeId: "Jxq_ejg3Snw",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/convert-an-array-to-reduced-form-set-1-simple-and-hashing/\n\nPractice Problem Online Judge: http://practice.geeksforgeeks.org/problems/convert-an-array-to-reduced-form/0\n\nThis video is contributed by Aditi Bainss\n\nPlease Like, Comment and Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-Zq1XLf5DTSo",
    topic: "Arrays",
    title: "Find the minimum value to be added so that array becomes balanced | GeeksforGeeks",
    youtubeId: "Zq1XLf5DTSo",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/find-the-minimum-value-to-be-added-so-that-array-becomes-balanced/\n\nPractice Problem Online Judge: http://practice.geeksforgeeks.org/problems/balanced-array/0\n\nThis video is contributed by Sagar Khurana\n\nPlease Like, Comment and Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-viaha1SnpT4",
    topic: "Arrays",
    title: "Array Rotation | GeeksforGeeks",
    youtubeId: "viaha1SnpT4",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/array-rotation/\n\nPractice Problem Online Judge:\nhttp://practice.geeksforgeeks.org/problems/rotate-and-delete/0\n\nThis video is contributed by Aditi Bainss\n\nRead More:https://www.geeksforgeeks.org/array-rotation/\n\nPlease Like, Comment and Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-5CRbjH0PmeE",
    topic: "Arrays",
    title: "Find the element that appears once where every other element appears twice | GeeksforGeeks",
    youtubeId: "5CRbjH0PmeE",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/find-element-appears-array-every-element-appears-twice/\n\nThis video is contributed by Shubham Kumar\n\nPlease Like, Comment and Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-GY-KULykGaw",
    topic: "Arrays",
    title: "Find subarray with given sum | Set 1 (Non-negative Numbers) | GeeksforGeeks",
    youtubeId: "GY-KULykGaw",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/find-subarray-with-given-sum/\n\nPractice Problem Online Judge: http://practice.geeksforgeeks.org/problems/subarray-with-given-sum/0\n\nThis video is contributed by Shubham Kumar\n\nRead More: https://www.geeksforgeeks.org/find-subarray-with-given-sum/\n\n\nPlease Like, Comment and Share the Video among your friends.\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-cjDlvwRSCPw",
    topic: "Arrays",
    title: "Merge an array of size n into another array of size m+n | GeeksforGeeks",
    youtubeId: "cjDlvwRSCPw",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/merge-one-array-of-size-n-into-another-one-of-size-mn/\n\nThis video is contributed by Parikshit Kumar Pruthi\n\nPlease Like, Comment and Share the Video among your friends.\n\nFollow us on Facebook:\nhttps://www.facebook.com/GfGVideos/\n\nAnd Twitter:\nhttps://twitter.com/gfgvideos\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-0fo7goi2GEg",
    topic: "Arrays",
    title: "Find four elements that sum to a given value | Set 1 (n^3 solution) | GeeksforGeeks",
    youtubeId: "0fo7goi2GEg",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/find-four-numbers-with-sum-equal-to-given-sum/\n\nPractice Problem Online Judge: http://practice.geeksforgeeks.org/problems/four-elements/0\n\nThis video is contributed by Shubham Kumar\n\nPlease Like, Comment and Share the Video among your friends.\n\nFollow us on Facebook:\nhttps://www.facebook.com/GfGVideos/\n\nAnd Twitter:\nhttps://twitter.com/gfgvideos\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-BTgxpaBHQuc",
    topic: "Arrays",
    title: "Find four elements that sum to a given value | Set 2 (n^2 Logn Solution) | GeeksforGeeks",
    youtubeId: "BTgxpaBHQuc",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/find-four-elements-that-sum-to-a-given-value-set-2/\n\nPractice Problem Online Judge: http://practice.geeksforgeeks.org/problems/find-all-four-sum-numbers/0\n\nThis video is contributed by Shubham Kumar\n\nPlease Like, Comment and Share the Video among your friends.\n\nFollow us on Facebook:\nhttps://www.facebook.com/GfGVideos/\n\nAnd Twitter:\nhttps://twitter.com/gfgvideos\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-G0ocgTgW464",
    topic: "Arrays",
    title: "Find subarray with given sum | Set 2 (Handles Negative Numbers) | GeeksforGeeks",
    youtubeId: "G0ocgTgW464",
    description: "Find subarray with given sum | Set 1 (Non-negative Numbers) : https://www.youtube.com/watch?v=GY-KULykGaw\n\nFind Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/find-subarray-with-given-sum-in-array-of-integers/\n\nPractice Problem Online Judge: http://practice.geeksforgeeks.org/problems/subarray-range-with-given-sum/0\n\nThis video is contributed by Shubham Kumar\n\nPlease Like, Comment and Share the Video among your friends.\n\nFollow us on Facebook:\nhttps://www.facebook.com/GfGVideos/\n\nAnd Twitter:\nhttps://twitter.com/gfgvideos\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-rd43j78S10A",
    topic: "Arrays",
    title: "Print All Distinct Elements of a given integer array | GeeksforGeeks",
    youtubeId: "rd43j78S10A",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/print-distinct-elements-given-integer-array/\n\nPractice Problem Online Judge: http://practice.geeksforgeeks.org/problems/make-a-distinct-digit-array/0\n\nThis video is contributed by Shubham Kumar\n\nRead More:https://www.geeksforgeeks.org/print-distinct-elements-given-integer-array/\n\nPlease Like, Comment and Share the Video among your friends.\n\nFollow us on Facebook:\nhttps://www.facebook.com/GfGVideos/\n\nAnd Twitter:\nhttps://twitter.com/gfgvideos\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-0-p-yzlWKUk",
    topic: "Arrays",
    title: "Quickly find multiple left rotations of an array | GeeksforGeeks",
    youtubeId: "0-p-yzlWKUk",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/quickly-find-multiple-left-rotations-of-an-array/\n\nPractice Problem Online Judge: http://practice.geeksforgeeks.org/problems/quick-left-rotation/0\n\nThis video is contributed by Aditi Bainss\n\nPlease Like, Comment and Share the Video among your friends.\n\nFollow us on Facebook:\nhttps://www.facebook.com/GfGVideos/\n\nAnd Twitter:\nhttps://twitter.com/gfgvideos\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-9k0vT6lx9XA",
    topic: "Arrays",
    title: "Find the minimum element in a sorted and rotated array | GeeksforGeeks",
    youtubeId: "9k0vT6lx9XA",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/find-minimum-element-in-a-sorted-and-rotated-array/\n\nPractice Problem Online Judge: http://practice.geeksforgeeks.org/problems/minimum-element-in-a-sorted-and-rotated-array/0\n\nThis video is contributed by Aditi Bainss\n\nPlease Like, Comment and Share the Video among your friends.\n\nFollow us on Facebook:\nhttps://www.facebook.com/GfGVideos/\n\nAnd Twitter:\nhttps://twitter.com/gfgvideos\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-dX1h7QBhYZ0",
    topic: "Arrays",
    title: "Delete an element from array (Using two traversals and one traversal) | GeeksforGeeks",
    youtubeId: "dX1h7QBhYZ0",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/delete-an-element-from-array-using-two-traversals-and-one-traversal/\n\nThis video is contributed by Shubham Kumar\n\nPlease Like, Comment and Share the Video among your friends.\n\nFollow us on Facebook:\nhttps://www.facebook.com/GfGVideos/\n\nAnd Twitter:\nhttps://twitter.com/gfgvideos\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-rpZfxmHTvJc",
    topic: "Arrays",
    title: "Find if there is a subarray with 0 sum | GeeksforGeeks",
    youtubeId: "rpZfxmHTvJc",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/find-if-there-is-a-subarray-with-0-sum/\n\nPractice Problem Online Judge:https://practice.geeksforgeeks.org/problems/subarray-with-0-sum/0\n\nThis video is contributed by Shubham Kumar\n\nPlease Like, Comment and Share the Video among your friends.\n\nFollow us on Facebook:\nhttps://www.facebook.com/GfGVideos/\n\nAnd Twitter:\nhttps://twitter.com/gfgvideos\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-s60sUkWh7TI",
    topic: "Arrays",
    title: "Find the smallest missing number | GeeksforGeeks",
    youtubeId: "s60sUkWh7TI",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/find-the-first-missing-number/\n\nThis video is contributed by Shubham Kumar\n\nPlease Like, Comment and Share the Video among your friends.\n\nFollow us on Facebook:\nhttps://www.facebook.com/GfGVideos/\n\nAnd Twitter:\nhttps://twitter.com/gfgvideos\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-9nX2mIFJMpE",
    topic: "Arrays",
    title: "Find the first repeating element in an array of integers | GeeksforGeeks",
    youtubeId: "9nX2mIFJMpE",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/find-first-repeating-element-array-integers/\n\nPractice Problem Online Judge: https://practice.geeksforgeeks.org/problems/first-repeating-element/0\n\nThis video is contributed by Shubham Kumar\n\nPlease Like, Comment and Share the Video among your friends.\n\nFollow us on Facebook:\nhttps://www.facebook.com/GfGVideos/\n\nAnd Twitter:\nhttps://twitter.com/gfgvideos\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-pWASJvFqBW0",
    topic: "Arrays",
    title: "Rearrange an array in maximum minimum form | Set 1 | GeeksforGeeks",
    youtubeId: "pWASJvFqBW0",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/rearrange-array-maximum-minimum-form/\n\nPractice Problem Online Judge: https://practice.geeksforgeeks.org/problems/-rearrange-array-alternately/0\n\nThis video is contributed by Shubham Kumar\n\nPlease Like, Comment and Share the Video among your friends.\n\nInstall our Android App:\nhttps://play.google.com/store/apps/details?id=free.programming.programming&hl=en\n\nFollow us on Facebook:\nhttps://www.facebook.com/GfGVideos/\n\nAnd Twitter:\nhttps://twitter.com/gfgvideos\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-Glv9KXC0lgE",
    topic: "Arrays",
    title: "Find the Increasing subsequence of length three with maximum product | GeeksforGeeks",
    youtubeId: "Glv9KXC0lgE",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/increasing-subsequence-of-length-three-with-maximum-product/\n\nThis video is contributed by Shubham Kumar\n\nPlease Like, Comment and Share the Video among your friends.\n\nInstall our Android App:\nhttps://play.google.com/store/apps/details?id=free.programming.programming&hl=en\n\nFollow us on Facebook:\nhttps://www.facebook.com/GfGVideos/\n\nAnd Twitter:\nhttps://twitter.com/gfgvideos\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-ZXpYPeRE66E",
    topic: "Arrays",
    title: "k-th smallest absolute difference of two elements in an array | GeeksforGeeks",
    youtubeId: "ZXpYPeRE66E",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/k-th-smallest-absolute-difference-two-elements-array/\n\nPractice Problem Online Judge:https://practice.geeksforgeeks.org/problems/smallest-absolute-difference/0\n\nThis video is contributed by Shubham Kumar\n\nPlease Like, Comment and Share the Video among your friends.\n\nInstall our Android App:\nhttps://play.google.com/store/apps/details?id=free.programming.programming&hl=en\n\nFollow us on Facebook:\nhttps://www.facebook.com/GfGVideos/\n\nAnd Twitter:\nhttps://twitter.com/gfgvideos\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-qHGpfJPQ0xY",
    topic: "Arrays",
    title: "Find the Rotation Count in Rotated Sorted array | GeeksforGeeks",
    youtubeId: "qHGpfJPQ0xY",
    description: "Find Complete Code at GeeksforGeeks Article: http://www.geeksforgeeks.org/find-rotation-count-rotated-sorted-array/\n\nThis video is contributed by Shubham Kumar\n\nPlease Like, Comment and Share the Video among your friends.\n\nInstall our Android App:\nhttps://play.google.com/store/apps/details?id=free.programming.programming&hl=en\n\nFollow us on Facebook:\nhttps://www.facebook.com/GfGVideos/\n\nAnd Twitter:\nhttps://twitter.com/gfgvideos\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-R745JLPox_A",
    topic: "Arrays",
    title: "A Product Array Puzzle | GeeksforGeeks",
    youtubeId: "R745JLPox_A",
    description: "Find Complete Code at GeeksforGeeks Article: https://www.geeksforgeeks.org/a-product-array-puzzle/\n\nPractice Problem Online Judge: https://practice.geeksforgeeks.org/problems/product-array-puzzle/0\n\nThis video is contributed by Shubham Kumar\n\nPlease Like, Comment and Share the Video among your friends.\n\nInstall our Android App:\nhttps://play.google.com/store/apps/details?id=free.programming.programming&hl=en\n\nFollow us on Facebook:\nhttps://www.facebook.com/GfGVideos/\n\nAnd Twitter:\nhttps://twitter.com/gfgvideos\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-RglGlzkliNM",
    topic: "Arrays",
    title: "Find an array element such that all elements are divisible by it | GeeksforGeeks",
    youtubeId: "RglGlzkliNM",
    description: "Find Complete Code at GeeksforGeeks Article: https://www.geeksforgeeks.org/number-among-n-numbers-numbers-divisible/\n\nThis video is contributed by Afzal Ansari\n\nPlease Like, Comment and Share the Video among your friends.\n\nInstall our Android App:\nhttps://play.google.com/store/apps/details?id=free.programming.programming&hl=en\n\nFollow us on Facebook:\nhttps://www.facebook.com/GfGVideos/\n\nAnd Twitter:\nhttps://twitter.com/gfgvideos\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-CPTbMozK2jA",
    topic: "Arrays",
    title: "Find final value if we double after every successful search in array | GeeksforGeeks",
    youtubeId: "CPTbMozK2jA",
    description: "Find Complete Code at GeeksforGeeks Article: https://www.geeksforgeeks.org/find-final-value-if-we-double-after-every-successful-search-in-array/\n\nThis video is contributed by Afzal Ansari\n\nPlease Like, Comment and Share the Video among your friends.\n\nInstall our Android App:\nhttps://play.google.com/store/apps/details?id=free.programming.programming&hl=en\n\nFollow us on Facebook:\nhttps://www.facebook.com/GfGVideos/\n\nAnd Twitter:\nhttps://twitter.com/gfgvideos\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-WRh6MmQLnpk",
    topic: "Arrays",
    title: "Largest number that is not a perfect square | GeeksforGeeks",
    youtubeId: "WRh6MmQLnpk",
    description: "Find Complete Code at GeeksforGeeks Article: https://www.geeksforgeeks.org/largest-number-not-perfect-square/\n\nThis video is contributed by Afzal Ansari\n\nPlease Like, Comment and Share the Video among your friends.\n\nInstall our Android App:\nhttps://play.google.com/store/apps/details?id=free.programming.programming&hl=en\n\nFollow us on Facebook:\nhttps://www.facebook.com/GfGVideos/\n\nAnd Twitter:\nhttps://twitter.com/gfgvideos\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt--u67D8oY9fg",
    topic: "Arrays",
    title: "Minimum swaps required to Sort Binary array | GeeksforGeeks",
    youtubeId: "-u67D8oY9fg",
    description: "Find Complete Code at GeeksforGeeks Article: https://www.geeksforgeeks.org/minimum-swaps-required-sort-binary-array/\n\nThis video is contributed by Parikshit Kumar Pruthi\n\nRead More: https://www.geeksforgeeks.org/minimum-swaps-required-sort-binary-array\n\nPlease Like, Comment and Share the Video among your friends.\n\nInstall our Android App:\nhttps://play.google.com/store/apps/details?id=free.programming.programming&hl=en\n\nIf you wish, translate into local language and help us reach millions of other geeks:\nhttp://www.youtube.com/timedtext_cs_panel?c=UC0RhatS1pyxInC00YKjjBqQ&tab=2\n\nFollow us on Facebook:\nhttps://www.facebook.com/GfGVideos/\n\nAnd Twitter:\nhttps://twitter.com/gfgvideos\n\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-EOw1Of_ZwPU",
    topic: "Arrays",
    title: "Count minimum number of subsets (or subsequences) with consecutive numbers | GeeksforGeeks",
    youtubeId: "EOw1Of_ZwPU",
    description: "Find Complete Code at GeeksforGeeks Article: https://www.geeksforgeeks.org/count-minimum-number-subsets-subsequences-consecutive-numbers/\n\nThis video is contributed by Parikshit Kumar Pruthi\n\nPlease Like, Comment and Share the Video among your friends.\n\nInstall our Android App:\nhttps://play.google.com/store/apps/details?id=free.programming.programming&hl=en\n\nIf you wish, translate into local language and help us reach millions of other geeks:\nhttp://www.youtube.com/timedtext_cs_panel?c=UC0RhatS1pyxInC00YKjjBqQ&tab=2\n\nFollow us on Facebook:\nhttps://www.facebook.com/GfGVideos/\n\nAnd Twitter:\nhttps://twitter.com/gfgvideos\n\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-ep8yXQ7xVcE",
    topic: "Arrays",
    title: "Sort all even numbers in ascending order and odd numbers in descending order | GeeksforGeeks",
    youtubeId: "ep8yXQ7xVcE",
    description: "Find Complete Code at GeeksforGeeks Article: https://www.geeksforgeeks.org/sort-even-numbers-ascending-order-sort-odd-numbers-descending-order/\n\nPractice Problem Online Judge:\nhttps://practice.geeksforgeeks.org/problems/sort-in-specific-order/0\n\nThis video is contributed by Parikshit Kumar Pruthi\n\nPlease Like, Comment and Share the Video among your friends.\n\nInstall our Android App:\nhttps://play.google.com/store/apps/details?id=free.programming.programming&hl=en\n\nIf you wish, translate into local language and help us reach millions of other geeks:\nhttp://www.youtube.com/timedtext_cs_panel?c=UC0RhatS1pyxInC00YKjjBqQ&tab=2\n\nFollow us on Facebook:\nhttps://www.facebook.com/GfGVideos/\n\nAnd Twitter:\nhttps://twitter.com/gfgvideos\n\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-3fYcADmz0cM",
    topic: "Arrays",
    title: "Find all elements that appear more than n/k times in an array | GeeksforGeeks",
    youtubeId: "3fYcADmz0cM",
    description: "Find Complete Code at GeeksforGeeks Article: https://www.geeksforgeeks.org/given-an-array-of-of-size-n-finds-all-the-elements-that-appear-more-than-nk-times/\n\nPractice Problem Online Judge: https://practice.geeksforgeeks.org/problems/count-element-occurences/1\n\nThis video is contributed by Parikshit Kumar Pruthi\n\nPlease Like, Comment and Share the Video among your friends.\n\nInstall our Android App:\nhttps://play.google.com/store/apps/details?id=free.programming.programming&hl=en\n\nIf you wish, translate into local language and help us reach millions of other geeks:\nhttp://www.youtube.com/timedtext_cs_panel?c=UC0RhatS1pyxInC00YKjjBqQ&tab=2\n\nFollow us on Facebook:\nhttps://www.facebook.com/GfGVideos/\n\nAnd Twitter:\nhttps://twitter.com/gfgvideos\n\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-9-3BXsfrpbY",
    topic: "Arrays",
    title: "Sliding Window Technique | GeeksforGeeks",
    youtubeId: "9-3BXsfrpbY",
    description: "Our courses : \nhttps://practice.geeksforgeeks.org/courses\n\nThis video is contributed by Anant Patni.\n\nRead More: https://www.geeksforgeeks.org/window-sliding-technique/\n\nPlease Like, Comment and Share the Video among your friends.\n\nInstall our Android App:\nhttps://play.google.com/store/apps/details?id=free.programming.programming&hl=en\n\nIf you wish, translate into local language and help us reach millions of other geeks:\nhttp://www.youtube.com/timedtext_cs_panel?c=UC0RhatS1pyxInC00YKjjBqQ&tab=2\n\nFollow us on Facebook:\nhttps://www.facebook.com/GfGVideos/\n\nAnd Twitter:\nhttps://twitter.com/gfgvideos\n\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-JTANbaSiw7s",
    topic: "Arrays",
    title: "Writing base cases in Recursion |  GeeksforGeeks",
    youtubeId: "JTANbaSiw7s",
    description: "Link to the course: https://practice.geeksforgeeks.org/courses/dsa-self-paced\nPlease Like, Comment and Share the Video among your friends.\r\n\r\nInstall our Android App:\r\nhttps://play.google.com/store/apps/details?id=free.programming.programming&hl=en\n\nRead More: https://www.geeksforgeeks.org/what-is-base-case-in-recursion/\r\n\r\nIf you wish, translate into local language and help us reach millions of other geeks:\r\nhttp://www.youtube.com/timedtext_cs_panel?c=UC0RhatS1pyxInC00YKjjBqQ&tab=2\r\n\r\nFollow us on Facebook:\r\nhttps://www.facebook.com/GfGVideos/\r\n\r\nAnd Twitter:\r\nhttps://twitter.com/gfgvideos\r\n\r\n\r\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-nK7SLhXcqRo",
    topic: "Arrays",
    title: "Naive Algorithm for Pattern Searching | GeeksforGeeks",
    youtubeId: "nK7SLhXcqRo",
    description: "Our courses : \nhttps://practice.geeksforgeeks.org/courses/\n\nThis video is contributed by Meenal Agrawal.\n\nRead More: https://www.geeksforgeeks.org/naive-algorithm-for-pattern-searching/\n\n\nPlease Like, Comment and Share the Video among your friends.\n\nInstall our Android App:\nhttps://play.google.com/store/apps/details?id=free.programming.programming&hl=en\n\nIf you wish, translate into the local language and help us reach millions of other geeks:\nhttp://www.youtube.com/timedtext_cs_panel?c=UC0RhatS1pyxInC00YKjjBqQ&tab=2\n\nFollow us on Facebook:\nhttps://www.facebook.com/GfGVideos/\n\nAnd Twitter:\nhttps://twitter.com/gfgvideos\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-gwmitwgz87s",
    topic: "Arrays",
    title: "Matrix Chain Multiplication | GeeksforGeeks",
    youtubeId: "gwmitwgz87s",
    description: "Our courses : \nhttps://practice.geeksforgeeks.org/courses/\n\nRead More: https://www.geeksforgeeks.org/matrix-chain-multiplication-dp-8/\n\nThis video is contributed by Meenal Agrawal.\n\nPlease Like, Comment and Share the Video among your friends.\n\nInstall our Android App:\nhttps://play.google.com/store/apps/details?id=free.programming.programming&hl=en\n\nIf you wish, translate into the local language and help us reach millions of other geeks:\nhttp://www.youtube.com/timedtext_cs_panel?c=UC0RhatS1pyxInC00YKjjBqQ&tab=2\n\nFollow us on Facebook:\nhttps://www.facebook.com/GfGVideos/\n\nAnd Twitter:\nhttps://twitter.com/gfgvideos\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-8dzfZNUnvJ8",
    topic: "Arrays",
    title: "Minimum Cost Path Problem | GeeksforGeeks",
    youtubeId: "8dzfZNUnvJ8",
    description: "Our courses : \nhttps://practice.geeksforgeeks.org/courses/\n\nRead More: https://www.geeksforgeeks.org/min-cost-path-dp-6/\n\nThis video is contributed by Meenal Agrawal.\n\nPlease Like, Comment and Share the Video among your friends.\n\nInstall our Android App:\nhttps://play.google.com/store/apps/details?id=free.programming.programming&hl=en\n\nIf you wish, translate into the local language and help us reach millions of other geeks:\nhttp://www.youtube.com/timedtext_cs_panel?c=UC0RhatS1pyxInC00YKjjBqQ&tab=2\n\nFollow us on Facebook:\nhttps://www.facebook.com/GfGVideos/\n\nAnd Twitter:\nhttps://twitter.com/gfgvideos\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-oqdttaJ_C6o",
    topic: "Arrays",
    title: "Cutting a rod problem | GeeksforGeeks",
    youtubeId: "oqdttaJ_C6o",
    description: "Our courses : \nhttps://practice.geeksforgeeks.org/courses/\n\nThis video is contributed by Meenal Agrawal.\n\nPlease Like, Comment and Share the Video among your friends.\n\nInstall our Android App:\nhttps://play.google.com/store/apps/details?id=free.programming.programming&hl=en\n\nIf you wish, translate into local language and help us reach millions of other geeks:\nhttp://www.youtube.com/timedtext_cs_panel?c=UC0RhatS1pyxInC00YKjjBqQ&tab=2\n\nFollow us on Facebook:\nhttps://www.facebook.com/GfGVideos/\n\nAnd Twitter:\nhttps://twitter.com/gfgvideos\n\nAlso, Subscribe if you haven't already! :)",
  },
  {
    id: "yt-m-Dqu7csdJk",
    topic: "Arrays",
    title: "Maximum of all subarrays of size 'k' using Sliding Window Technique | GeeksforGeeks",
    youtubeId: "m-Dqu7csdJk",
    description: "Our courses : \nhttps://practice.geeksforgeeks.org/courses/ \n\nRead More: https://www.geeksforgeeks.org/sliding-window-maximum-maximum-of-all-subarrays-of-size-k/\n\nThis video is contributed by Meenal Agrawal.\n\nPlease Like, Comment and Share the Video among your friends.\n\nInstall our Android App:\nhttps://play.google.com/store/apps/details?id=free.programming.programming&hl=en\n\nIf you wish, translate into the local language and help us reach millions of other geeks:\nhttp://www.youtube.com/timedtext_cs_panel?c=UC0RhatS1pyxInC00YKjjBqQ&tab=2\n\nFollow us on Facebook:\nhttps://www.facebook.com/GfGVideos/\n\nAnd Twitter:\nhttps://twitter.com/gfgvideos\n\nAlso, Subscribe if you haven't already! :)\n#geeksforgeeks",
  },
  {
    id: "yt-NKoHjWl2m8Y",
    topic: "Arrays",
    title: "Smallest subarray with sum greater than a given value | GeeksforGeeks",
    youtubeId: "NKoHjWl2m8Y",
    description: "Explanation for the article: http://www.geeksforgeeks.org/minimum-length-subarray-sum-greater-given-value/\n\nThis video is contributed by Harshit Jain.",
  },
// IMPORTED_VIDEOS_END
];

export const topics = ['Arrays', 'Linked Lists', 'Stacks & Queues', 'Trees', 'Graphs', 'Dynamic Programming'];

export function getVideosByTopicSlug(slug: string) {
  const normalized = slug.replace(/-/g, ' ').toLowerCase();
  return videoLibrary.filter((v) => v.topic.toLowerCase() === normalized);
}

export function getTopicNameFromSlug(slug: string) {
  const normalized = slug.replace(/-/g, ' ').toLowerCase();
  const found = topics.find((t) => t.toLowerCase() === normalized);
  return found || slug;
}
